name: 'version-docs'
description: "Automatically version and deploy your repository's docs"
inputs:
  doc-location:
    description: 'The location of the docs relative to the root of your repo'
    required: true
    default: 'docs'
  doc-branch:
    description: 'The branch on which to store your versioned documentation'
    required: true
    default: 'gh-pages'
  commit-msg:
    description: 'The branch on which to store your versioned documentation'
    required: true
    default: 'docs: versioned docs via version-docs'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'bin/index.js'